# Generated by Django 2.0.3 on 2018-03-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_document_seul'),
    ]

    operations = [
        migrations.CreateModel(
            name='nombre_fichiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comptage', models.IntegerField(default=9)),
            ],
        ),
    ]
