# Generated by Django 2.0.3 on 2018-03-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_nombre_fichiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nombre_fichiers',
            name='comptage',
            field=models.IntegerField(),
        ),
    ]
